import { createRequire } from 'node:module'
import { join } from 'node:path'

const testRunnerResult = await Bun.build({
	entrypoints: ['./vendor/testrunner/testRunner.ts'],
	format: 'esm',
	minify: true,
})

for (const res of testRunnerResult.outputs) {
	const content = await res.text()

	Bun.write(join('src', 'modules', 'build', 'test-lib.js'), content)

	console.info('test lib generated')
}

// The sandbox mounts the decimal.js source into the virtual file system, so the
// source must be a string in the package instead of a file on disk. A file on
// disk is not readable in a worker thread bundle or in the Temporal workflow vm.
const require = createRequire(import.meta.url)
const decimalSource = await Bun.file(require.resolve('decimal.js/decimal.mjs')).text()
const decimalVersion = require('decimal.js/package.json').version

Bun.write(
	join('src', 'modules', 'generated', 'decimal.js'),
	[
		`// Generated by vendor.ts from decimal.js ${decimalVersion}. Do not edit.`,
		'/** @type {string} */',
		`const decimalJsSource = ${JSON.stringify(decimalSource)}`,
		'export default decimalJsSource',
		'',
	].join('\n'),
)

console.info(`decimal.js ${decimalVersion} module generated`)
